### ISSUE TITLE
Cannot set helm values for keys containing '.'

### ISSUE THREAD

**Issue by jarnfast** [MChorfa/porter-helm3#14]
In version 0.1.9 the following hack was introduced:

https://github.com/MChorfa/porter-helm3/blob/0f59e5d93563eb68449812c46533054c9b1023f4/pkg/helm3/install.go#L125-L130

This appears to escape any `.` found in the keys for helm causing helm not to be able to override the wanted values.

From porter.yaml:
```
 - helm3:
      description: "Install Harbor"
      name: harbor
      chart: ./charts/harbor.tgz
      namespace: harbor
      replace: true
      wait: true
      set:
        database.external.host: "{{ bundle.parameters.database_host }}"
       <snipped>
      values:
        - valuefiles/harbor.yaml
```

Example from 0.1.8:
```
/cnab/app/mixins/helm3/helm3-runtime install --debug
/usr/local/bin/helm3 helm3 install harbor ./charts/harbor.tgz --namespace harbor --replace --wait \
  --values valuefiles/harbor.yaml --set database.external.host=host.docker.internal \
  <snipped>
```

Example from 0.1.9+:
```
/cnab/app/mixins/helm3/helm3-runtime install --debug
/usr/local/bin/helm3 helm3 install harbor ./charts/harbor.tgz --namespace harbor --replace --wait \
  --values valuefiles/harbor.yaml --set database\.external\.host=host.docker.internal \
  <snipped>
```

Expected outcome is that the rendered charts use `host.docker.internal` but actual behavior is that they're rendered using the default value defined in the chart's values.yaml.

**Comment by squillace** [comment]
@MChorfa fixed #8 but left the issue open, sure seems related. Ultimately, the issue is a helm issue that is bleeding through to the yaml. https://github.com/helm/helm/issues/4030

**Comment by jarnfast** [comment]
@squillace hmm. yes. Point is that the escaping introduced appears to cause more problems than they fix ;-)

Ie. with 0.1.9 setting parameters with a regular tree structure key is not possible.

**Comment by squillace** [comment]
I guess we should go with the --param-file? It should work.

**Comment by squillace** [comment]
I have another chart with blah[0].images= line, because there can be more than one, and that blows in the yaml, too. Can't escape it for the life of me.

**Comment by jarnfast** [comment]
> I guess we should go with the --param-file? It should work.

You mean let the helm3 mixin construct a file from the porter set of parameters? 

I'm a happy camper as long as it works and allows me to specify value files and installation specific parameter overrides in the porter.yaml

**Comment by MChorfa** [comment]
I will have to revert back the hack of escaping :disappointed: . It has a side effect of nullifying the keys. Meaning if the key is defined in the default values file defined as follow:
```yaml
defaultBackend:
    nodeSelector:
        beta.kubernetes.io/os
```
and if we try to set it by escaping it `defaultBackend\.nodeSelector\."beta\\.kubernetes\\.io/os"=linux` helm can't find the key and completely ignore the key override.
So if we want to override complexe keys. we have no choice to create a values file as follow:
```yaml
defaultBackend:
    nodeSelector:
        beta.kubernetes.io/os: "linux"
controller:
    nodeSelector:
        beta.kubernetes.io/os: "linux"
    service:
        annotations:
            service.beta.kubernetes.io/azure-dns-label-name: "dns"
```
And then pass it to step action like :
```yaml
install:
  - helm3:
      description: "Upgrade porter-nginx"
      name: porter-nginx
      chart: stable/nginx-ingress
      version: 1.41.3
      namespace: "{{ bundle.parameters.namespace }}"
      upsert: true
      values:
        - "./values.yaml" <----------- all my complexe defs
      set:
        controller.scope.namespace: "{{ bundle.parameters.namespace }}"
        controller.ingressClass: "{{ bundle.parameters.namespace }}-nginx"
```
