### ISSUE TITLE
can't build aarch64 due to missing OpenAPIv2

### ISSUE THREAD

**Issue by squillace** [MChorfa/porter-helm3#15]
git clone
make build

```
github.com/MChorfa/porter-helm3/pkg/helm3 imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/discovery imports
        github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.3), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
make: *** [Makefile:46: generate] Error 1
```
Either I'd like to build it, or you can cross-build and push a release for ARM64?

pinebook pro
Manjaro ARM
go version go1.15.2 linux/arm64

**Comment by MChorfa** [comment]
Done: https://github.com/MChorfa/porter-helm3/releases/tag/v0.1.12

**Comment by squillace** [comment]
this like will have to pull in by arch: https://github.com/MChorfa/porter-helm3/blob/81bab7e414f1908f9fdffda6c6f8bd325c097e11/pkg/helm3/build.go#L69

otherwise the mixin binary is arch64 but not helm3. :-) No hurry. Was checking to see how far I could go on porter on aarch64 -- really, really far. I'm building and running stuff on it now....

**Comment by MChorfa** [comment]
@squillace Now you can :) ... please re download v.1.12 and configure as follow:
```yaml
- helm3:
    clientVersion: v3.3.4
    clientPlatfrom: linux #Must Match the base porter Platform
    clientArchitecture: amd64 | arm64 #Must Match the base porter Architecture
```
