### ISSUE TITLE
Does this mixin support login to private registry?

### ISSUE THREAD

**Issue by hoangmnsd** [MChorfa/porter-helm3#29]
Thank you for providing this mixin, 
I am working on a project that need using private ACR (Azure).
It pulls helm chart from external ACR so it need to authenticate to ACR first.
But It seem this mixin doesn't support flag `registry login`? is it? 

I am using `exe` mixin to run bash shell commands to login. But I think it'd better if helm3 mixin support that feature.

**Comment by carolynvs** [comment]
No, that command isn't supported. 

It would be great to see the helm3 mixin support what some of the other mixins do: running arbitrary commands through the mixin (see this [example](https://porter.sh/mixins/az/#mixin-syntax)), so that you could do something like this:

```yaml
helm3:
  arguments:
    - registry
    - login
```

All of the mixins use the exec mixin under the hood, it's just a matter of exposing that so that people don't need to use the exec mixin to run commands that weren't explicitly supported.

Another thought is that now that we support buildkit, we should design how we can mount secrets during `porter build` so that we can do things like pull a private chart and embed it into the bundle. That way the chart is available at runtime without having to specify credentials to use the chart at runtime.

**Comment by MChorfa** [comment]
Starting v0.1.14 you can perform this as follow: 
```yaml
login:
  - helm3:
      description: "Login to OCI registry"
      arguments:
        - registry
        - login
        - localhost:5000
        - "--insecure"
      flags:
        u: myuser
        p: mypass

```
