### ISSUE TITLE
--create-namespace flag is always set

### ISSUE THREAD

**Issue by lucasmaheo** [MChorfa/porter-helm3#50]
The `--create-namespace` flag is always set, even when the namespace exists. The default behaviour for helm in that case is to try creating the namespace. However in some environments, users do not have the rights to create namespaces, resulting in an error:
```
Error: INSTALLATION FAILED: namespaces is forbidden: User "myuser" cannot create resource "namespaces" in API group "" at the cluster scope
```
I suggest adding the option to set it or not, potentially depending on a bundle parameter, in order to leave the choice to the end user.

**Comment by carolynvs** [comment]
```yaml
install:
- helm3:
     chart: ...
     namespace: myns
     create-namespace: false # default to true, preserves existing behavior
```

I am not a fan of making boolean config values that default to true, but it lines up well with the name of the flag, and we are already doing it for the atomic flag too so I feel like that would be most consistent.

What do you think?
