### ISSUE TITLE
Can't escape these very common set lines

### ISSUE THREAD

**Issue by squillace** [MChorfa/porter-helm3#8]
Either I want to know how to escape these using Helm3 and porter, or if it's an issue let's fix it!

the node selectors MUST be escaped in that fashion in order to work correctly on the command line. How should they be created in YAML using the Helm3 mixin in order to work correctly? 

```
# Create namespace for the harbor nginx ingress controller 
kubectl create namespace harbor-ingress-system

# Add the nginx helm repo
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

# Install nginx ingress for Harbor
helm install harbor-nginx-ingress ingress-nginx/ingress-nginx \
    --namespace harbor-ingress-system \
    --set controller.ingressClass=harbor-nginx \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
```

**Comment by MChorfa** [comment]
The issue is actually coming from helm is stripping escaping from literal key  https://github.com/helm/helm/issues/4030
So patch was introduced within the version v0.1.9 where  fix force the escaping at runtime :
You still define your action as follow: 
```yaml
install:
  - helm3:
      description: "Upgrade porter-nginx"
      name: porter-nginx
      chart: stable/nginx-ingress
      version: 1.41.3
      namespace: "{{ bundle.parameters.namespace }}"
      upsert: true
      set:
        controller.scope.namespace: "{{ bundle.parameters.namespace }}"
        controller.ingressClass: "{{ bundle.parameters.namespace }}-nginx"
        defaultBackend.nodeSelector."beta\.kubernetes\.io/os": "linux"
        controller.nodeSelector."beta\.kubernetes\.io/os": "linux"
        controller.nodeSelector."kubernetes\.io/role": "main"
```
---
And at runtime it would result to : 
```shell
/cnab/app/mixins/helm3/helm3-runtime install --debug
/usr/local/bin/helm3 helm3 upgrade --install porter-nginx stable/nginx-ingress --namespace porter --version 1.41.3 --set controller\.ingressClass=porter-nginx --set controller\.nodeSelector\."beta\\.kubernetes\\.io/os"=linux --set controller\.nodeSelector\."kubernetes\\.io/role"=main --set controller\.scope\.namespace=porter --set defaultBackend\.nodeSelector\."beta\\.kubernetes\\.io/os"=linux
```
---
```shell
Execution completed successfully!
NAME              CREATED         MODIFIED        LAST ACTION   LAST STATUS
nginx             5 seconds ago   5 seconds ago   install       succeeded
```
Will keep this open until helm introduce  `--set-literal ` option
